sonar.projectKey=tp-jenkins
sonar.sources=.
sonar.language=py
sonar.host.url=http://host.docker.internal:9000
sonar.token=sqp_72348d5e856024d05a46a7ed70caaeb526ef2947
sonar.exclusions=**/*.html,**/*.htm
